tags:
    - Products
summary: Create Products
description: Create Products
parameters:
    - in: header
      name: Authorization
      schema:
          type: string
          format: JWT
          example: Bearer <JWT>
      description: JWT Token
      required: true
    - name: request
      in: body
      required: true
      schema:
          type: object
          properties:
              name:
                  type: string
                  example: "name"
              description:
                  type: string
                  example: "description"
              image_url:
                  type: string
                  example: "www.google.com"
              price:
                  type: integer
                  example: 100
              stock:
                  type: integer
                  example: 10
              category_id:
                  type: integer
                  example: 1
              weight_kg:
                  type: float
                  example: 0.5
              length_cm:
                  type: integer
                  example: 10
              width_cm:
                  type: integer
                  example: 10
              height_cm:
                  type: integer
                  example: 10
              product_type:
                  type: integer
                  enum: [1, 2]
                  example: 0
responses:
    201:
        description: Product created successfully
        schema:
            type: object
            properties:
                message:
                    type: string
                    example: Product created successfully
    400:
        description: Failed to pass validation process
        schema:
            type: object
            properties:
                error:
                    type: string
                    example: Unauthorized
    500:
        description: Something wrong with the database.
        schema:
            type: object
            properties:
                error:
                    type: string
                    example: Cannot connect to the database.
